added description for sunburst graph
knowit/folk-webapp pull request #114
Opened 2021-01-11 14:19 UTC by fridaklockmann

2021-01-11 14:56 UTC, HeleneSemmerud commented on src/pages/Competence.tsx
> +        gjennomsnittligs score for hver underkategori og forholdet mellom underkategoriene i samme hovedkategori"
I tillegg vises grennomsnittlig score*

2021-01-11 14:57 UTC, HeleneSemmerud reviewed
Se kommentar

2021-01-11 14:59 UTC, a-knowit requested changes

2021-01-11 14:59 UTC, a-knowit commented on src/pages/Competence.tsx
> +        gjennomsnittligs score for hver underkategori og forholdet mellom underkategoriene i samme hovedkategori"
`I tillegg vises gjennomsnittlig score `*

2021-01-11 15:09 UTC, a-knowit approved these changes

2021-01-12 07:27 UTC, vebovs approved these changes

2021-01-12 08:11 UTC, merged