Feature/new design for expanded cell
knowit/folk-webapp pull request #136
Opened 2021-02-04 15:02 UTC by fridaklockmann

2021-02-11 09:17 UTC, a-knowit requested changes
Mye å gå i gjennom. Anbefaler å få en til til å gå over.

2021-02-11 09:17 UTC, a-knowit commented on src/data/components/table/DataTable.tsx
> +  const rowRenderer = (props: {
Linter klager på manglende props validation

2021-02-11 09:17 UTC, a-knowit commented on src/data/DDTable.tsx
> +    passedFilters === motFilterLength + comFilterLength && newRows.push(row);
Linter ønsker seg en `let` for deklareringen av passedFilters litt lengre opp

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +          competenceUrl: 'falskUrl.com',
Bedre å bruke eget domene, selv om det bare er placeholder og domene ikke er i bruk i dag.
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +          competenceUrl: 'falskUrl.com',
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +          competenceUrl: 'falskUrl.com',
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +            competenceUrl: 'falskUrl.com',
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +          competenceUrl: 'falskUrl.com',
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.test.tsx
> +          competenceUrl: 'falskUrl.com',
Bruk f.eks. `/404` i stedet.

2021-02-11 09:17 UTC, a-knowit commented on src/components/EmployeeInfo.tsx
> +    if (!list || list === undefined) return <NoData />;
Vil ikke `!list` alltid være true om `list` er `undefined`? I så fall er det redundant å sjekke begge.

2021-02-11 09:17 UTC, a-knowit commented on src/data/DDTable.tsx
> +    passedFilters === motFilterLength + comFilterLength && newRows.push(row);
Linje `226` er `if` statementen i feil rekkefølge. Sjekk om `rowSkills` er definert først.

2021-02-11 15:12 UTC, thoasc commented on src/data/components/table/DataTable.tsx
> +  const rowRenderer = (props: {
En mulig løsning for å please ESLint her er å type `rowRenderer` som `TableRowRenderer` (importere fra `react-virtualized`), og så destrukturere props inne i parentesene:
```suggestion
  const rowRenderer: TableRowRenderer = ({
    className,
    index,
    key,
    rowData,
    style,
  }) => {
    // Trenger ikke destrukturere inne i funksjonen
    const id = rows[index].rowId;
```

(Husk i tilfelle å importere typen: `import { AutoSizer, Column, Table, TableRowRenderer } from 'react-virtualized';`)

2021-02-11 17:37 UTC, thoasc reviewed
Vet ikke om det har noe med denne PR-en å gjøre, men det kan virke som det er noe som ikke helt fungerer med aggregeringen av dataene til radar-diagrammet brukt i `EmployeeInfo.tsx`? Det kan se ut som det spesifikt gjelder for kategoriene IoT og AI/data.

Jeg åpner f.eks. opp Aksel Langø Karlsen eller Andreas Bade, og i visningen "Hovedkategorier" er disse to kategoriene 0, mens dersom man snevrer seg inn på enten IoT eller AI/data, viser diagrammet verdier. Har bare gjort stikkprøver, så vet ikke om det kan gjelde for andre kategorier også.

2021-02-12 07:46 UTC, fridaklockmann commented on src/data/components/table/DataTable.tsx
>      columns.length === 5 ? consultantTableWidths[index] : widthList[index];
Nei, du har rett, den er ikke nødvendig lenger!

2021-02-12 11:14 UTC, thoasc approved these changes

2021-02-12 12:09 UTC, merged