enhancement/rewrite-api-communication
knowit/folk-webapp pull request #229
Opened 2021-12-15 08:59 UTC by Lekesoldat

See [#545](https://github.com/knowit/Dataplattform-issues/issues/545) for further information.﻿

2021-12-21 13:28 UTC, MaPoKen approved these changes
LGTM!

Ligger et par unødvendige kommentarer her og der men ellers ser alt good ut og virka som før

2021-12-21 16:28 UTC, Jonas-C requested changes
Har ikke sett på om API-typene er riktig eller ikke.

2021-12-21 16:28 UTC, Jonas-C commented on src/api/data/competence/competenceQueries.ts
> +    revalidateOnFocus: false,
Hvis dette skal være standard, hadde det kanskje vært greit å legge det inn i global-configen?

2021-12-21 16:28 UTC, Jonas-C commented on src/api/data/dataClient.ts
> +      console.log('Request aborted due to not being able to renew token.')
Samme kritikk som i authClient.

2021-12-21 16:28 UTC, Jonas-C commented on src/api/data/employee/employeeApi.ts
> +export const getEmployeeExperience = (url: string, user_id: string) =>
Foreslår at man holder seg til camelCase, i og med at det er vanligst i JavaScript. Hvis API'et krever snake_case kan vi heller skjule det fra resten av appen her.

2021-12-21 16:28 UTC, Jonas-C commented on src/api/data/employee/employeeApiTypes.ts
> +// employeeRadar has same response as CompetenceAreasResponse
Kunne laget et type alias, i tilfelle dette ikke alltid vil være tilfellet. Kan spare noe tid.

2021-12-21 16:28 UTC, Jonas-C commented on src/api/data/employee/employeeQueries.ts
> +// https://stackoverflow.com/questions/54938236/can-you-early-return-with-react-hooks/56976469#56976469
Hvorfor er denne kommentaren her? Relatert til noe som [dette](https://github.com/vercel/swr/discussions/876)?

2021-12-21 16:28 UTC, Jonas-C commented on src/api/other/client.ts
> +import axios from 'axios'
Ser ikke helt poenget med denne. Den er prikk lik den andre klienten, bare med en annen BASE_URL. Tror man like greit kan kombinere denne med den andre, og heller spesifisere /data/ i hookene som tar i bruk den. Blir keitete å oppdatere to forskjellige klienter hver gang en endring skal skje.

2021-12-21 16:28 UTC, Jonas-C commented on src/context/UserInfoContext.tsx
> +  user: UserInfo | null
Tror man kan få typet denne til å bare være `UserInfo`, så man slipper å non-null-asserte der den skal brukes. Den vil jo tross alt enten kaste en feil i dev eller være non-null.

2021-12-21 16:28 UTC, Jonas-C commented on src/context/UserInfoContext.tsx
> +      value={{ user: fetchedUser, setUser: setFetchedUser }}
Tror det kan være en god ide å holde `setUser` inne i UserInfoContext, og heller eksponere funksjoner som kan sette den dersom alt er som det skal.

2021-12-21 16:28 UTC, Jonas-C commented on src/utils/ApiDebugger.tsx
> +const ApiDebugger = () => {
Trengs denne filen?

2021-12-21 16:28 UTC, Jonas-C commented on src/pages/login/LoginPage.tsx
> +    window.location.replace('/auth/login')
Foretrekker `push` her. Da kan jeg gå tilbake hvis jeg har trykket på 'logg inn' ved en feil.

2021-12-21 16:28 UTC, Jonas-C commented on tsconfig.json
> +  "include": ["src", "tsconfig.json", "src/api/data/.tsx"],
Hvorfor er `src/api/data/.tsx` lagt inn her? Vil ikke src/**/* dekke alt?

2021-12-21 16:28 UTC, Jonas-C commented on tsconfig.json
> +  "exclude": ["node_modules", "backend", "backend/**/*.js"]
Samme her, tipper backend kan exludes fullstendig med `backend/**/*`. Tror heller ikke man skal eksludere node_modules.

2021-12-21 16:28 UTC, Jonas-C commented on src/components/Content.tsx
> +
Det kunne vært lurt å lage en ProtectedRoute-komponent istedenfor. Da slipper vi en "all or nothing"-løsning som vil koste mye å endre i fremtiden.

2021-12-21 16:39 UTC, Lekesoldat commented on src/components/Content.tsx
> +
Tar dette i en egen PR. 
Vil da også fikse en ny og penere login-side.

2021-12-21 16:40 UTC, Lekesoldat commented on src/pages/login/LoginPage.tsx
> +    window.location.replace('/auth/login')
Ref. det vi pratet om i Slack.
Vil ikke fungere med React Router sånn som /auth/login er implementert nå.

2021-12-21 17:39 UTC, Lekesoldat commented on .vscode/extensions.json
>  }
I dette repoet er .vscode/ satt opp med extension-recommendations og settings for å sikre likt utviklingsmiljø for alle som bruker vscode i prosjektet. Derfor pushet slik at folk skal få muligheten til å ha følge like konvensjoner mm. Ingen personlige settings fra min side er pushet.

2021-12-21 17:41 UTC, Lekesoldat commented on src/components/LoginLogoutButton.tsx
>        window.location.replace('/auth/login')
https://github.com/knowit/folk-webapp/pull/229#discussion_r773288002

2021-12-21 17:47 UTC, Lekesoldat commented on src/api/auth/authHelpers.ts
> +}
Døne

2021-12-21 17:48 UTC, Lekesoldat commented on src/components/Content.tsx
> +        {/* <ApiDebugger /> */}
Døne

2021-12-21 18:04 UTC, Lekesoldat commented on tsconfig.json
> +  "include": ["src", "tsconfig.json", "src/api/data/.tsx"],
Har ikke rørt dette, - aner egentlig ikke hvorfor det står slik. Forsøker å gjøre en endring.

2021-12-21 18:04 UTC, Lekesoldat commented on tsconfig.json
> +  "exclude": ["node_modules", "backend", "backend/**/*.js"]
Døne. 
Tror node modules må være der afaik.

2021-12-21 18:08 UTC, Lekesoldat commented on src/api/auth/authHelpers.ts
> +export const getAccessTokenExpiresAt = () => {
Døne

2021-12-21 18:10 UTC, Lekesoldat commented on src/api/auth/authHelpers.ts
> +export const isAccessTokenValid = () => {
Døne

2021-12-21 18:14 UTC, Lekesoldat commented on src/api/auth/authHelpers.ts
> +  const user = useUserInfo()
det funker, men burde ikke gjøres når du sier det. Skriver om!

2021-12-21 18:21 UTC, Lekesoldat commented on src/api/auth/authHelpers.ts
> +
Døne

2021-12-21 18:22 UTC, Lekesoldat commented on src/api/data/competence/competenceApiTypes.ts
> +interface FagtimeDataPoint {
Jeg er helt enig, men har per nå bare brukt navnene slik de er definert i endepunktene. Tenker navneendring kanskje er en del av en større omskrivning og ikke essensielt for denne?

2021-12-21 18:22 UTC, Lekesoldat commented on src/api/data/competence/competenceQueries.ts
> +    isLoading: !error && !data,
Har du et forslag til hvordan?

2021-12-21 18:24 UTC, Lekesoldat commented on src/api/data/competence/competenceQueries.ts
> +    revalidateOnFocus: false,
Enn så lenge er jeg usikker på om vi skal ha det disablet. Enig i at det ikke burde repeteres x ganger, men akkurat nå er jeg noe usikker på hva som burde gjøres. Ideellt sett er det jo digg å ha det på, men vet ikke om det blir dyrt kostnadsmessig.

2021-12-21 18:24 UTC, Lekesoldat commented on src/api/data/dataClient.ts
> +      console.log('Request aborted due to not being able to renew token.')
Notert.

2021-12-21 18:33 UTC, Lekesoldat commented on src/api/data/employee/employeeApi.ts
> +export const getEmployeeExperience = (url: string, user_id: string) =>
Døne.
API trenger det, men input tas nå som camelCase

2021-12-21 18:34 UTC, Lekesoldat commented on src/api/data/employee/employeeQueries.ts
> +// https://stackoverflow.com/questions/54938236/can-you-early-return-with-react-hooks/56976469#56976469
Fikset.

2021-12-21 18:42 UTC, Lekesoldat commented on src/api/other/client.ts
> +import axios from 'axios'
Døne.

Gjorde data-klienten til den generiske, og slang heller på `/data` prefix i endepunktene der det var relevant. Beholdt other-mappen i tilfelle det dukker opp flere ting lignende på /privacyPolicy som ikke faller innunder tydelige kategorier som /auth og /data mm.

2021-12-21 18:45 UTC, Lekesoldat commented on src/context/UserInfoContext.tsx
> +  user: UserInfo | null
Veldig mye av auth-flyten og headeren sitt  layout dreier seg om hvorvidt en user er satt eller ikke. en user settes ikke før man er logget inn, så det gir veldig mening at det kan være null.

2021-12-21 18:47 UTC, Lekesoldat commented on src/context/UserInfoContext.tsx
> +      value={{ user: fetchedUser, setUser: setFetchedUser }}
Mulig jeg ikke helt forstår hva du mener nå. 

`user` settes av seg selv ved et kall til backenden, men `setUser` brukes til å cleare user i context på logout feks.

2021-12-21 18:47 UTC, Lekesoldat commented on src/utils/ApiDebugger.tsx
> +const ApiDebugger = () => {
Gøne, but never førgøtten.

2021-12-21 21:01 UTC, Lekesoldat commented
Da skal alt være endret opp i 💯

2021-12-21 21:09 UTC, Lekesoldat commented on src/api/other/client.ts
> +import axios from 'axios'
EDIT:
Dette så vi på sammen så du vet nå hvordan hele flyten ble også mtp. error handling <3

2021-12-22 18:26 UTC, Jonas-C commented on src/context/UserInfoContext.tsx
> +      value={{ user: fetchedUser, setUser: setFetchedUser }}
Isåfall ville jeg hatt en logout-funksjon som rydder opp at. Da er det Provideren som er ansvarlig for dette, og ikke den som konsumerer provideren.

2021-12-22 18:33 UTC, Jonas-C commented on src/api/data/competence/competenceQueries.ts
> +    isLoading: !error && !data,
`isValidating` er true når ny data hentes.

2021-12-22 18:56 UTC, Jonas-C approved these changes
LGTM

2021-12-22 18:56 UTC, merged