Enhancement/refactor table structure
knowit/folk-webapp pull request #247
Opened 2022-01-27 09:57 UTC by MaPoKen

Fixes https://github.com/knowit/Dataplattform-issues/issues/562

Hva har blitt gjort:
- Prøvd å type mer spesifikt hva som er per nå i datatabellene
- Skrevet om fra å bruke DDItem for både `DDTable` og `DDChart`, kun `DDItem`. Det gjør prop handling lettere
- Tok i bruk nye hooks for å hente data for grafene

2022-02-02 12:17 UTC, aspleym commented on src/pages/customer/CustomerList.tsx
> +  const createDropwDowns = useCallback(
Du vil kanskje endre navnet på denne?

2022-02-02 12:17 UTC, aspleym commented on src/pages/customer/CustomerList.tsx
> +    createDropwDowns(grouped, !expand)
Her også

2022-02-02 13:45 UTC, Lekesoldat requested changes

2022-02-02 13:45 UTC, Lekesoldat commented on src/data/components/table/DataTable.tsx
> +type RowIndex = { index: number }
interface?

2022-02-02 13:45 UTC, Lekesoldat commented on src/pages/customer/CustomerList.tsx
> +  const pending = employeeData === undefined
```suggestion
  const pending = !error && !employeeData
```

2022-02-02 13:45 UTC, Lekesoldat commented on src/pages/customer/CustomerList.tsx
> +  const { data: employeeData } = useEmployeeTable()
```suggestion
  const { data: employeeData, error } = useEmployeeTable()
```

2022-02-02 13:46 UTC, Lekesoldat commented
Er også en merge conflict som du kanskje ser

2022-02-04 09:58 UTC, AudunBerget commented on src/pages/customer/CustomerList.tsx
> +  const createDropwDowns = useCallback(
Det er kanskje litt utenfor scopet til denne PR-en, men her bør vel egentlig componentene lages i renderingen, også holder heller staten på verdiene som trengs for å lage componentene.

2022-02-04 10:03 UTC, AudunBerget commented on src/data/types.tsx
> +  fetchHook: () => SWRResponse
Dette bør vel heller være en payload, slik at componentene ikke er bundet til å gjøre et kall.

2022-02-04 11:28 UTC, MaPoKen commented on src/data/types.tsx
> +  fetchHook: () => SWRResponse
Slik Competence er satt opp så må var det den måten ellers må man fetche alt før man viser frem grafene.

2022-02-09 07:30 UTC, Lekesoldat approved these changes
lgtm

2022-02-09 08:20 UTC, merged