Feature/cv download dialog
knowit/folk-webapp pull request #31
Opened 2020-09-28 14:10 UTC by fridaklockmann

2020-09-28 14:42 UTC, jkrmc12 requested changes

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +    handleDownlaodLink(); // This will be executed when `language` or 'fileType' state changes
```suggestion
      if (fileType === ".pdf"){
        if (language === "Norsk") setDownloadLink(data.no_pdf);
        else setDownloadLink(data.int_pdf); 
      }
      else{
        if (language === "Norsk") setDownloadLink(data.no_word);
        else setDownloadLink(data.int_word); 
      }
```

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +  const [downloadLink, setDownloadLink] = React.useState(data.int_pdf);
```suggestion
  const [fileType, setFileType] = useState(".pdf");
  const [language, setLanguage] = useState("Norsk");
  const [downloadLink, setDownloadLink] = useState(data.int_pdf);
```

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +  }, [language,fileType])// eslint-disable-line react-hooks/exhaustive-deps
Hvorfor må denne regelen ignoreres?

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +  const handleClose = () => {
Unødvendig funksjon, bruk onClose direkte

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +    handleDownlaodLink(); // This will be executed when `language` or 'fileType' state changes
Unødvendig funksjon

2020-09-28 14:42 UTC, jkrmc12 commented on src/data/components/table/cells/CvCell.tsx
> +    <CvDialog name = {"Fornavn Etternavn"} data = {data} />
> "Fornavn Etternavn" 

?

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CharacterLimitBox.tsx
> +  if (e === null) return false;
Hvis `e` kan være `null` burde det være synlig i typen også  `HTMLSpanElement | null`

2020-09-28 14:42 UTC, jkrmc12 commented on src/components/CvDialog.tsx
> +function SimpleDialog({onClose, data, name, open }: {data: CvCellData, onClose:Function, name:string, open:boolean }){
`SimpleDialog` er et litt intetsigende navn

2020-09-29 11:36 UTC, fridaklockmann commented on src/data/components/table/cells/CvCell.tsx
> +    <CvDialog name = {"Fornavn Etternavn"} data = {data} />
Hvordan henter man på best mulig måte ut navnet på personen her?

2020-09-29 11:41 UTC, jkrmc12 commented on src/data/components/table/cells/CvCell.tsx
> +    <CvDialog name = {"Fornavn Etternavn"} data = {data} />
Ah, nå forstår jeg. Jeg _tror_ data fra hele tabell-raden også blir sendt ned til custom render-komponenter, hvis ikke så er det mulig å patche

2020-09-30 08:53 UTC, jkrmc12 commented
https://github.com/knowit/folk-webapp/pull/33

2020-09-30 08:53 UTC, closed without merging