Feature/customer home page
knowit/folk-webapp pull request #480
Opened 2023-05-15 11:36 UTC by palmanshaus

2023-05-15 12:58 UTC, rauboti requested changes
_EmployeeTable.tsx_
Generelt vil jeg anbefaler å ikke endre innhold på variabelen som henter data til en komponent. Det kan føre til at man mister oversikten over hva variabelen inneholder, skape bugs, osv. Her, på linje 35, mottar vi employeeData fra useEmployeeTable(). Denne burde bli stående som const, også bør du enten sjekke og sette en variabel slik:

```
let tablePayload;
if (customerSpecific) {
  tablePayload = employeeData.filter((row) => row['rowData'][3].customer == customerId)
} else {
  tablePayload = employeeData
}
```

Eller bare legge uttrykket på payload på komponenten:

`payload={customerSpecific ? employeeData.filter((row) => row['rowData'][3].customer == customerId) : employeeData}`

Jeg tror jeg liker den siste best, ettersom den allerede også er ligger bak en sjekk på at employeeData finnes. Den er heller ikke så lang at det tar mye plass i return-statement.

_CustomerCard.tsx_
Her er det en del dobbel kode når du genererer ut kortet med konsulenter og timer. Alt er identisk med unntak av sx-property på Box-elementet. Her burde innholdet (BoxInfo ++) være en egen komponent som kan ta imot consultants, billedLastPeriod og billedTotalFixedNumber som properties. For enkelhets skyld kan du legge den komponenten i samme fil (siden akkurat det oppsettet er spesifikt til CustomerCard, og nok ikke vil bli brukt utenom, og da trenger du heller ikke exporte den). Så legger du bare den inn i Box-delen.

Teksten inne i komponenten er også litt klemt sammen, så mer luft burde utnyttes på sidene der (det er jo plass til mer tekst mellom kantene). Prøv også å sette margin på BoxInfo-delene for å prøve å få litt luft mellom tall og neste overskrift. 5 ish pixler burde holde.

2023-05-16 06:55 UTC, rauboti commented
Ser mye er løst etter ønske, og også med detaljen om å bare ta sx-property helt ut og la den være en variabel utafor som et alternativ til forslagene. Bra. Er et par ting jeg allikevel vil pirke videre på

_EmployeeTable.tsx_
Ser det henger igjen en liten detalj her på linje 35. Denne kan endres tilbake fra let til const (som er å foretrekke for denne variabelen) og da kan du også fjerne // eslint-disable.... på linje 34.
Dette er på ingen måte breaking, men ryddig kode er fin kode.

_CustomerSpesificHoursBilledGraph.tsx_
Her er det mye felles kode med fila CustomerOverview.tsx, noe som skyldes et par forskjellige ting. Jeg tror kanskje mye kan være gjort ved å rydde litt i alle useEffectene. Først; jeg tenker at den kunde-spesifikke sida kan bruke samme local storage keypairs for start og slutt dato som det kundeoversikts-sida bruker (og det er uansett enkelt å implementere igjen seinare, skulle det bli behov for det). Men det jeg kanskje ville gjort, er å lage en hjelpefil under util. Den kan f.eks. hete local-storage-tokens.ts, og den kan inneholde funksjonene (som dermed kan importeres til både CustomerOverview og CustomerSpesificHoursBilledGraph). Det er generelt en fin praksis å samle utility-kode som brukes flere steder og importere dem slik at selve komponenten er ryddigst mulig.
Det er også mulig å redusere antall useEffect-funksjoner. Både den som henter startDato (linje 11) og den som henter sluttdato (linke 36) kjører kun når komponenten lastes (dvs, ingen av de har noen dependancy i arrayet etter funksjonen). Da kan også funksjonene ligge i samme useEffect (som isolert kun sparer 2 linjer kode, men det blir litt ryddigere allikevel). Tilsvarende i CustomerOverview, som har samme "problem". De to som setter / fjerner tokens har forskjellige avhengigheter og må nok derfor også fortsatt være separert. Men det blir allerede mye ryddigere om de hentes fra util-fil heller enn å stå kodet hver for seg.

Når dette er done, ser det så langt OK ut for meg, tenker jeg.

2023-05-16 23:47 UTC, rauboti commented
Har committed følgende endringer til denne PRen:
- Bygget om CustomerCard-komponenten slik at vertical (boolean) er en egen property, ikke nødvendigvis avhengig av om den er spesifikk for 1 kunde. Den struktureres nå forskjellig om den er vannrett eller loddrett, slik at forskjellig lengde / linjer allikevel skal se bra ut vannrett. Til det formålet er det brukt Grid istedetfor Box fra MUI, sida den passer bedre til slikt formål. Har også brukt `<p>` over `<div>` for visning av tekst.
- Rettet en typo i OpenInNewIcon eksporten + filer som den importeres til
- Endret hvordan CustomerCard brukes conditionally i CustomerSiteContent for å unngå gjentagende kode.
- Fikset posisjonering av OpenInNewIcon på Kunder > Listevisning slik at den er mer i tråd med hvordan vi viser for ansatte (og dermed også ryddigere)
- Fikset posisjonering av OpenInNewIcon på Kunder > Overordnet oversikt slik at den er mer i tråd med hvordan vi viser for ansatte (og dermed også ryddigere)
- Endret ledetekst til avkrysningen for vis i graf slik at den er i en `<label>` og ikke en `<div>`, og med htmlFor-property angitt, av hensyn til UU.

2023-05-22 06:20 UTC, henrikav approved these changes

2023-05-22 06:55 UTC, rauboti approved these changes

2023-05-22 06:56 UTC, merged