Fix/graph legends overlap
knowit/folk-webapp pull request #494
Opened 2023-05-30 10:40 UTC by mariehessen

Customized the legends to change into new row when there is more then four legends chosen. 
- For each of the rows I changed the translateY value to avoid them overlapping. 
- Added more space between legends by changing itemWidth and itemSpacing.

2023-05-31 07:36 UTC, rauboti requested changes
Nå har jeg med vilje valgt noen litt lengre navn, men det ser ut til at det er en overlap her enda:
![image](https://github.com/knowit/folk-webapp/assets/33912044/3676f80b-ec83-4436-871d-fddf589b6724)

Ser dette kan være en utfordring ettersom det er en SVG som blir renderet, og at du derfor ikke har noen god støtte for flexbox osv. Men lurer likevel på om det finnes noen alternative veier. Har du alternativt forsøkt å sette itemWidth dynamisk? Du har jo allerede det utfiltrerte objektet, og dermed også lengden på hva som skal inn
![image](https://github.com/knowit/folk-webapp/assets/33912044/b3936a1a-dec6-44b5-96f2-e50d44d771ad)

Så kan man finne ut hvem av disse som har lengst id ved hjelp av reduce, f.eks. slik
`const maxLength = filteredData.reduce((previous, current) => {
    return previous > current.id.toString().length
      ? previous
      : current.id.toString().length
  }, 0)`
  Og bruke den sammen med en koeffisient for å gange opp til passende bredde, jeg prøvde `itemWidth: maxLength * 6` med godt resultat, f.eks. Da har jeg også satt itemSpacing til 0, og så vil sjekken din på lengde kanskje kreve noe mer jobb, sida det da potensielt vil kunne være plass til mer enn 4 på første linje. Minuset er at alle vil være rigide satt til samme bredde, ikke bare den som trenger mest plass.
Et annet alternativ er å generere legend selv, utenfor nivo, dersom du klarer å få hentet ut riktige farger osv. Det er et eksempel på det her: https://codesandbox.io/s/frosty-ganguly-xnylc7
Akkurat denne approachen fungerte i 0.67.0 av Nivo, og ikke i nyere versjoner (vi bruker 0.83.0). Men kanskje du ser en alternativ vei til mål fra eksempelet der?

2023-05-31 07:42 UTC, rauboti commented
Et lite notat også, er at jeg ser `const filteredData = props.data` på linje 21 i LineChart.tsx. Jeg skjønner godt hvorfor, det er lettere å jobbe med når koden settes opp. Men kanskje er det hakket mer lesbart for nye som setter seg inn i komponenten hvis den er med fra toppen av. Om du f.eks. tar ut data sammen med isBig på toppen, og kun bruker data nedover. Alternativt `data as filteredData` dersom du mener data ikke er beskrivende nok for hva variabelen inneholder?

2023-06-07 13:18 UTC, rauboti commented
Stikkprøver ser bra ut for meg, iallefall.

2023-06-08 06:26 UTC, henrikav requested changes
Ser bra ut, men litt mismatch i fargene fra legends og tooltip :)

<img width="1180" alt="Screenshot 2023-06-08 at 08 17 30" src="https://github.com/knowit/folk-webapp/assets/26927941/43ede345-68a0-4a6b-b350-95664bda977f">

2023-06-09 08:27 UTC, rauboti approved these changes

2024-03-18 11:16 UTC, closed without merging

2024-03-18 11:16 UTC, OliverKnowit commented
løst i en annen branch