Feature/download filtered employee list
knowit/folk-webapp pull request #496
Opened 2023-06-01 09:09 UTC by palmanshaus

Give the user the option to download a filtered list of employees with info about filters and those employees

2023-06-01 15:06 UTC, rauboti requested changes
Jeg skal ta en nærmere titt på resten, men jeg ser jeg misset en ting for knappe-komponenten jeg ba deg kopiere. Den er ikke universelt utformet, og en skjermleser vil derfor aldri finne muligheten for å laste ned uttrekket (fordi en skjermleser ikke vil gjenkjenne at det er en knapp). Det er min feil, jeg har latt meg lure av komponentnavnet. Hvis du importerer Button fra mui/material og passer den inn istedetfor en vanlig div, så har også den komponenten et eget attribute for ikon, også kan du legge onClick-eventen på knappen istedetfor på ikonet. Og da er den universelt utformet i tillegg.

2023-06-02 12:08 UTC, rauboti commented
Litt pirk til brukergrensesnittet, så er vi i mål så langt jeg kan se:

- Det er nå en bindestrek som alltid er synlig under toppen, frem til det finnes noe som er utfiltrert. Den ser ut til å stamme fra NoData-komponenten. Den forsvinner når jeg begynner få et utvalg. Sjekk at den kun vises når det faktisk er en feilmelding med henting av data.
- Jeg trur ikke valgalternativene er helt beskrivende i nedlastningsdialogen. Vi snakka såvidt om det, men jeg var kanskje ikke konkret nok på hva jeg tenkte. Det er f.eks. vanskelig å forstå "Bruk default", og trekke konklusjon til at det har noe med filnavn å gjøre i det hele tatt. Også har jeg, trur jeg, et bedre default-filnavn. Så jeg ville endra svaralternativa til "Last ned som ansatte.xlsx" og "Angi annet filnavn (uten .xlsx)" som tekster. Også satt standardfilnavnet til "ansatte" istedetfor "filterOutput".

Resten ser nå bra ut.

2023-06-02 13:08 UTC, rauboti commented
Da ser det bra ut for meg

2023-06-02 13:31 UTC, henrikav requested changes
Ser bra ut, men valget "Last ned som ansatte.xlsx" navngir filen til filterOutput. 
For å gjenskape: 
1) Slett cookies 
2) Åpne modal for nedlastning 
3) Trykk på last ned med annet navn 
4) Trykk last ned som ansatte.xlsx.   

En ting til - Mulig at vi også burde disable laste ned-knappen for custom navn hvis tekstfelt er tomt.

2023-06-02 13:45 UTC, palmanshaus commented
@henrikav  Var visst liten glipp nå! Har fiksa opp i det du nevnte nå!

2023-06-02 14:02 UTC, henrikav approved these changes

2023-06-05 06:11 UTC, rauboti approved these changes

2023-06-05 06:17 UTC, merged