Feature/show number of consultants in hours billed graph
knowit/folk-webapp pull request #499
Opened 2023-06-06 12:01 UTC by palmanshaus

Make it possible to change between view of hours Billed and active consultants in the "Overordnet oversikt"-graph.
Additionally, I changed the view to make all buttons used in the graph the same style, as well as fixing some code I realised could've been done a lot easier

2023-06-07 06:42 UTC, rauboti reviewed
Det ser ut til at det i noen tilfeller er høyere antall konsulenter på enkelt uker enn måneden samlet. Har det vært diskutert, f.eks. med Tor, hvordan dette skal vises?

Eksempel: Vegvesen i perioden 1.1.2023 - 30.4.2023. Ingen måneder når over 6 konsulenter, men på et par enkeltuker er vi oppe på 8.

Har det vært avklart om vi skal:
- Vise høyeste antall
- Vise laveste antall
- Vise snitt for perioden rundet ned til nærmeste heltall (`Math.floor()`)

2023-06-07 13:28 UTC, rauboti commented
Mottatt på Slack via Pål; Tor ønsket at høyeste antall konsulent skulle være gjeldende for måned også (som er ordnet med siste commit).
Har ikke mer å utsette utover det.

2023-06-08 06:46 UTC, henrikav requested changes
Veldig god start, men jeg har noen innvendinger!

**Problem 1**: Det er veldig uklart for meg hvilket valg som er aktivt. Akkurat nå er det beige farge på det aktive valget, noe som ikke er naturlig siden bakgrunnsfargen også er beige. Alternativet blir da å eventuelt gjøre det motsatt slik at det aktive valget får fargen hvit. Videre kan det hende den valgte knappen burde være bedre uthevet eller en annen farge enn bare plain hvitfarge for å vise hva som er valgt, ettersom hvit brukes så mye ellers i løsningen også. Her må du nok prøve deg litt frem.

**Problem 2**: På bildet under viser løsningen at det er 88 konsulenter på Entur. Hvordan er det mulig når det bare er 29 konsulenter hos Entur?
<img width="880" alt="Screenshot 2023-06-08 at 08 43 21" src="https://github.com/knowit/folk-webapp/assets/26927941/2f227c6a-7fc9-4046-bbd8-6cef9ff123d2">

2023-06-08 07:34 UTC, palmanshaus commented
@henrikav 
Når det angår at Entur har 88 konsulenter på det punktet har jeg ikke noe innsikt i, men 29 konsulenter vil jo være det som gjelder hos dem per dags dato. Ser riktignok at det på dags dato i grafen vises at det er 43 som har fakturert timer hos Entur siste uke, kan jo ikke se nøyaktig hvem disse 43 er, men trodde de 29 som vises som konsulenter var de som har listet opp Entur som hovedkunde? I graf med oversikt over konsulenter vil man jo vises om man bare har ført en halvtime, som jeg typ antar og vil bidra til at folk som har ført opp salgsarbeid eller intervju hos dem og vil listes opp.

Skal se mer på farger av knapper

2023-06-08 10:18 UTC, henrikav requested changes
Fargene på knappen ser good ut nå! Angående antall konsulenter på Entur på forskjellige punkter så vil jeg helst at du undersøker det nærmere, fordi vi har innsikt i hvem som har ført disse timene. Da må du inn i Athena i AWS og kjøre litt spørringer. Jeg er helt enig at det kan være flere enn 29 stykk som har ført timer på Entur en uke, men jeg har vanskelig for å tro at det er 88, noe som er over halvparten av de som er ansatt i Objectnet. Det er litt derfor jeg har en anelse om at noe av dataen muligens er aggregert feil

2023-10-20 12:40 UTC, closed without merging