Feature/oppdater tabell for ansatt
knowit/folk-webapp pull request #502
Opened 2023-06-07 13:24 UTC by tfahsing

Use MUI table
- created configurable component for creating sortable tables
- removed unused components
- moved and reused some of the dataCell-components

2023-06-09 08:24 UTC, rauboti requested changes
Ser jevnt over bra ut, kun et par visuelle pirketing. Ved mouseover på celle, endres bakgrunnsfargen nå på deler av cella, ikke hele cella.
![image](https://github.com/knowit/folk-webapp/assets/33912044/29ead042-119c-4862-9dac-84849a47dd18)
Er det mulig å få bakgrunnsfargen helt ut på sidene ved mouseover tilsvarende? Sikkert bare en margin eller noe som må rettes.
Tilsvarende ser jeg at grafen i den utvida delen har vandra litt til venstre, så den er ikke lenger loddrett alignet til kolonne over:
![image](https://github.com/knowit/folk-webapp/assets/33912044/26628e87-7fe0-4816-8b6c-9ef412cf6fb5)

Jeg kunne ikke se noe mer i farta. Er dette ting det er mulig å gjøre noe med også?

2023-06-12 04:20 UTC, tfahsing commented
> Ser jevnt over bra ut, kun et par visuelle pirketing. Ved mouseover på celle, endres bakgrunnsfargen nå på deler av cella, ikke hele cella. ![image](https://user-images.githubusercontent.com/33912044/244635839-29ead042-119c-4862-9dac-84849a47dd18.png) Er det mulig å få bakgrunnsfargen helt ut på sidene ved mouseover tilsvarende? Sikkert bare en margin eller noe som må rettes. Tilsvarende ser jeg at grafen i den utvida delen har vandra litt til venstre, så den er ikke lenger loddrett alignet til kolonne over: ![image](https://user-images.githubusercontent.com/33912044/244636420-26628e87-7fe0-4816-8b6c-9ef412cf6fb5.png)
> 
> Jeg kunne ikke se noe mer i farta. Er dette ting det er mulig å gjøre noe med også? Utover det, syntes jeg det er jobba bra med å beholde utseendet, som ønsket.

Alt skal nå være fikset

2023-06-12 05:59 UTC, rauboti commented
Da ser det vel bra ut for meg. @henrikav tar også en titt.

2023-06-12 06:00 UTC, rauboti approved these changes

2023-06-12 06:21 UTC, henrikav requested changes
For meg brekker "Kunder"-siden når man trykker inn på den. Ellers ser det fint ut :)

2023-06-12 12:49 UTC, tfahsing commented
> For meg brekker "Kunder"-siden når man trykker inn på den. Ellers ser det fint ut :)

Har fikset det nå

2023-06-15 06:32 UTC, merged