Feature/virtalized table
knowit/folk-webapp pull request #52
Opened 2020-10-20 13:51 UTC by fridaklockmann

2020-10-20 13:53 UTC, fridaklockmann commented on src/data/components/table/DataTable2.tsx
> +               {/*  <> {columns[columnIndex].renderCell? columns[columnIndex].renderCell(cellData) :cellData}</> */}
Her har jeg lyst til å bruke funksjonen som ligger i renderCell, slik at den kan rendre den cellen som skal være her, men jeg får det ikke til å fungere. Får "Cannot invoke an object which is possibly 'undefined'"- feil, selv om jeg tester at det ikke er undefined først.

2020-10-27 12:29 UTC, fridaklockmann commented on src/data/components/table/DataTable2.tsx
> +                rowHeight = {getRowHeight}
Oppdateres ikke

2020-11-03 09:00 UTC, swape requested changes

2020-11-03 09:00 UTC, swape commented on src/components/EmployeeInfo.tsx
> +        ?roles.length > 0
oo.. nesta ternary... kan du lage heller en variabel utenfor return biten for det. Og det kan sikkert optimaliseres siden begge "false" verdiene returnerer samme data.

2020-11-03 09:00 UTC, swape commented on .vscode/settings.json
> +        "eyklhwdakrwew"
?.. hehe.. du kan fjerne hele den fila :)

2020-11-04 10:52 UTC, jkrmc12 requested changes
Hvis det er noe funksjonalitet som har falt ut som følge av denne omskrivingen så må du opprette nye saker på boardet om det

2020-11-04 10:52 UTC, jkrmc12 commented on package-lock.json
> +{
Slett denne, det er lockfilen for npm og vi bruker yarn

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/cells/ConsultantCell.tsx
> +    <div style={styles.root}>
Hvorfor må du bruke inline styles istedenfor classer laget av jss? (makeStyles, ..)

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/cells/CustomerStatusCell.tsx
> +    <div style={{display: 'flex', justifyContent: 'space-between', width:"100%"}}>
se kommentar om inline styles

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/cells/CvCell.tsx
> +interface consultantType{
Pascal case interface og typer

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/cells/ProjectStatusCell.tsx
> +    <div style={{ backgroundColor: '#EFEFEF',
se kommentar om inline styles

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/DataTable.tsx
> +            renderCell({ data, rowData })
`renderCell` er etter hva jeg kan se en react komponent og må derfor også brukes som en react-komponent 
```suggestion
          <renderCell data={data} rowData={rowData} />
```
Den brude også ha PascalCase navn som en React  komponent

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/DataTable.tsx
> +        {renderCell(cellData)}
Se kommentar om rendering av react-komponenter

2020-11-04 10:52 UTC, jkrmc12 commented on src/data/components/table/DataTable.tsx
> +      <div>{renderExpanded(cellData)}</div>
Se kommentar om render av react-kompoenter

2020-11-06 07:10 UTC, swape approved these changes

2020-11-06 10:43 UTC, jkrmc12 approved these changes

2020-11-06 10:44 UTC, merged