Adds images from cv-partner
knowit/folk-webapp pull request #77
Opened 2020-11-30 11:50 UTC by HeleneSemmerud

2020-11-30 12:01 UTC, HeleneSemmerud commented on backend/repository/util.js
> +
Denne funksjonen kunne med fordel vært i dataplattform/lib.js, men jeg fikk det ikke til å fungere.

2020-11-30 12:02 UTC, HeleneSemmerud commented on backend/repository/util.js
> +
Den kan sikkert skrives litt bedre også

2020-11-30 12:03 UTC, HeleneSemmerud commented on src/components/CvDialog.tsx
> +    } else if (language === 'Norsk') setDownloadLink(data.no_docx);
Her er problemet at siden det er en link beskyttet av jwt access_token så vil den gi 401 når man redirectes. Usikker på hvordan vi skal fikse det.

2020-11-30 12:05 UTC, HeleneSemmerud commented on backend/repository/data.js
> +        image: getStorageUrl(employee.image_key),
Det blir også en følgefeil i ConsultantCell.tsx pga. denne linken, fordi denne kan gi 404 om bilde ikke finnes og da blir ikke FallBackIcon rendret men initialene. Kan kanskje fikses med "children" for Material UI Avatar, men det fikk jeg ikke til. Får heller ikke Avatar til å svelge 404 meldingen og ikke spytte den ut i konsollen.

2020-12-10 11:41 UTC, a-knowit requested changes
Nedlasting av CV fungerer ikke. Går til `https://localhost:3000/undefined/private/{UUID}.pdf`.

Bilder fremvises ikke.

2021-01-26 10:25 UTC, closed without merging

2021-01-26 10:25 UTC, HeleneSemmerud commented
Gjort i annen branch